import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Router from "next/router";
import Header from "../components/header";
import Slider from "../components/slider";
import SimpleCard from "../components/simpleCard";
import image1 from "../public/assets/images/image-example.jpg";
import image2 from "../public/assets/images/image-example1.jpg";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Alexa tienda de ropa Americana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Slider />

      <div className={styles.container}>
        <div className={styles.gallery}>
          <SimpleCard
            image={image1}
            title="Ropa casual para damas"
            path="/About"
          />
          <SimpleCard
            image={image2}
            title="Para ellos"
            path="/About"
          />
          <SimpleCard
            image={image1}
            title="Ropa casual para damas"
            path="/About"
          />
          <SimpleCard
            image={image2}
            title="Ropa casual para damas"
            path="/About"
          />
                    <SimpleCard
            image={image2}
            title="Ropa casual para damas"
            path="/About"
          />
          <SimpleCard
            image={image1}
            title="Ropa casual para damas"
            path="/About"
          />
          <SimpleCard
            image={image2}
            title="Ropa casual para damas"
            path="/About"
          />
        </div>
      </div>
    </div>
  );
};

export default Home;
